version: 1.0.{build}
os: Visual Studio 2015
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: nuget pack Kulman.WPA81.BaseRestService\Kulman.WPA81.BaseRestService.csproj -Prop Configuration=Release
artifacts:
- path: '*.nupkg'
  name: NuGet.org  